youtube_mp3_site/models.py
# from flask import current_app

youtube_mp3_site/contact/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField 
from wtforms.validators import DataRequired, Length, ValidationError, Email


class EmailForm(FlaskForm):
    email = StringField('Enter email here:',
                validators=[DataRequired(), Email()])
    message = TextAreaField('Enter message:',
                validators=[DataRequired()])
    submit = SubmitField('Send Email')

youtube_mp3_site/download/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length, URL, ValidationError
import re


class YoutubeForm(FlaskForm):
    video = StringField('Enter valid Youtube video URL here:', 
                        validators=[DataRequired()])
    mp3_submit = SubmitField('Get MP3')
    video_submit = SubmitField('Get MP4')
    
    
    def validate_video(self, url):

        regex = (      
            r"[\[https*://\]*www\.]*"
            r"youtube.com\/watch\?v="
            r"[a-zA-Z0-9-._]{11}(?!&list=)"
            # r"(&list=[a-zA-Z0-9-._]{34}"
            # r"&index=[0-9]{1,4})*"
        )

        if not re.search(regex, str(url.data)):
            raise ValidationError("Invalid Youtube URL provided.")
    

youtube_mp3_site/__init__.py
from flask import Flask
from flask_mail import Mail
from youtube_mp3_site.config import Config

mail = Mail()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    mail.init_app(app)

    from youtube_mp3_site.errors.error_handlers import errors
    from youtube_mp3_site.general.routes import general
    from youtube_mp3_site.contact.routes import contact
    from youtube_mp3_site.download.routes import download
        
    app.register_blueprint(errors)
    app.register_blueprint(general)
    app.register_blueprint(contact)
    app.register_blueprint(download)
    

    return app

youtube_mp3_site/contact/routes.py
from flask import render_template, Blueprint, redirect, flash, send_file, send_from_directory, url_for
from youtube_mp3_site.contact.forms import EmailForm
from flask import request
from youtube_mp3_site.contact.utils import send_issue_email



contact = Blueprint('contact', __name__)

@contact.route('/contact', methods=['GET', 'POST'])
def send_contact():
    form = EmailForm()
    if form.validate_on_submit():
        send_issue_email(user=form.email, body=form.message)
        flash('Email successfully sent.', 'success')
    return render_template('contact.html', title='Contact', form=form)

youtube_mp3_site/download/routes.py
from flask import render_template, Blueprint, redirect, flash, send_file, send_from_directory, url_for, safe_join, request, Response
from youtube_mp3_site.download.forms import YoutubeForm
from youtube_mp3_site.download.yt_downloader import YoutubeDownloader
from youtube_mp3_site.config import Config as cfg
import io
import os

download = Blueprint('download', __name__)


@download.route('/download', methods=['GET', 'POST'])
def download_mp3():

    form = YoutubeForm()

    if form.validate_on_submit():        
        
        # Create YoutubeDownloader object
        video = YoutubeDownloader(str(form.video.data), form.mp3_submit.data)
        
        if form.mp3_submit.data:

            audio_clip_ret_data = io.BytesIO()

            with open(os.path.abspath("%s\\%s" % (cfg.PATH_TO, str(video.get_audio_clip))), 'rb') as fo:
                audio_clip_ret_data.write(fo.read())

            audio_clip_ret_data.seek(0)
            
            # remove files from path
            os.remove(os.path.abspath("%s\\%s" % (cfg.PATH_TO, str(video.get_audio_clip))))

            # send file
            return send_file(audio_clip_ret_data, 
                                as_attachment=True, 
                                attachment_filename=f'{video.new_title}.mp3',
                                mimetype='application/mp3')

        else:

            video_clip_ret_data = io.BytesIO()

            with open(os.path.abspath("%s\\%s" % (cfg.PATH_TO, str(video.get_video_clip))), 'rb') as fo:
                video_clip_ret_data.write(fo.read())
            video_clip_ret_data.seek(0)

            # remove files from path
            os.remove(os.path.abspath("%s\\%s" % (cfg.PATH_TO, str(video.get_video_clip))))

            return send_file(video_clip_ret_data, 
                                as_attachment=True,
                                attachment_filename=f'{video.new_title}.mp4',
                                mimetype='application/mp4')



    return render_template('download.html', title='Download', form=form)

youtube_mp3_site/general/routes.py
from flask import render_template, Blueprint
# from youtube_mp3_site.download.utils import send_issue_email


general = Blueprint('general', __name__)

@general.route('/')
@general.route('/home')
def home():
    return render_template('home.html')

@general.route('/about')
def about():
    return render_template('about.html', title='About')

youtube_mp3_site/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <form>
            <h3 class="font-weight-light mt-4 mb-4">Youtube MP3DL</h3>
            <p class="content font-weight-light">With this converter, you are able to get high quality mp3 audio files and mp4 video files, free of charge.</p>
            <p class="content font-weight-light">Simply provide the URL for the YouTube video (current build supports non-playlist only) in the Download page, and click the mp3 button for an audio file, or mp4 for a video file.</p>
        </form>
    </div>
{% endblock content %}

youtube_mp3_site/templates/contact.html
{% extends "layout.html" %}
{% block content %}

    <!-- Flash Messages -->
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="flashes ml-5 mr-5">
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}">{{ message }}</div>
        {% endfor %}
    </div>
    {% endif  %}
    {% endwith %} 

    <div class="col-md-6 font-weight-light content-section mx-auto">
        <form method="POST" action="">
            {{ form.csrf_token }} 
            <fieldset class="form-group">
                <legend class="border-bottom">
                    <div class="form-group mt-2">

                        <!-- Email Label -->
                        {{ form.email.label(class="form-control-label mb-4") }}
                        <!-- Email String Field -->
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">                            
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}                            
                            </div>
                            
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}

                        <!-- Email Message -->
                        {{ form.message.label(class="form-control-label mt-4") }}

                        <!-- Email Message Text Field -->
                        {% if form.message.errors %}
                            {{ form.message(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">                            
                                {% for error in form.message.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}                            
                            </div>
                            
                        {% else %}
                            {{ form.message(class="form-control form-control-lg mt-4 mb-4") }}
                        {% endif %}

                        
                    </div>
                </legend>
            </fieldset>
            <div class="form-group">              
                <!-- Submit Email Button-->
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
        
    </div>
{% endblock content %}

youtube_mp3_site/templates/download.html
{% extends "layout.html" %}
{% block content %}

<div class="col-md-6 font-weight-light content-section mx-auto">
    <form method="POST" action="">
        {{ form.csrf_token }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">
                <div class="form-group mt-5">
                    {{ form.video.label(class="form-control-label") }}
                    
                    {% if form.video.errors %}
                        {{ form.video(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">                            
                            {% for error in form.video.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}                            
                        </div>
                        
                    {% else %}
                        {{ form.video(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </legend>
        </fieldset>
        <div class="form-group">
            {{ form.mp3_submit(class="btn btn-outline-info") }}
            {{ form.video_submit(class="btn btn-outline-info") }}
        </div>
    </form>
    
</div>

{% endblock content %}

youtube_mp3_site/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <form>
            <h1 class="font-weight-light mb-4">Have a YouTube video you want to download?</h3>
            <p class="content font-weight-light">With this converter, you are able to get high quality mp3 audio files and mp4 video files, free of charge. To continue, click on the Download section.</p>
        </form>
    </div>
{% endblock content %}

youtube_mp3_site/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
    crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if page_title %}
        <title>Youtube MP3DL - {{ title }}</title>
    {% else %}
        <title>Youtube MP3DL</title>
    {% endif %}
    
</head>
<body>
    <header class="site-header">

      <nav class="font-weight-light navbar navbar-expand-md navbar-dark bg-primary fixed-top">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <a class="navbar-brand" href="{{ url_for('general.home') }}">Youtube MP3 Converter</a>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="{{ url_for('general.home') }}">Home</a>
            <a class="nav-item nav-link" href="{{ url_for('download.download_mp3') }}">Download</a>
            <a class="nav-item nav-link" href="{{ url_for('general.about') }}">About</a>
            <a class="nav-item nav-link" href="{{ url_for('contact.send_contact') }}">Contact</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav ml-auto">          
            <a class="nav-item nav-link" style="cursor: pointer;" href="https://www.github.com/nintendude64">
              <img src="{{ url_for('static', filename='img/github_logo.png') }}" alt="github" width="35" />
            </a>
          
          </div>
        </div>

        

      </nav>
    </header>
    {% block content %}
    {% endblock content %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>